contactandtodo/contact/urls.py
from django.urls import path

from . import views
app_name = 'contact'

urlpatterns = [
    path('',views.index, name = 'index'),
    path('newperson/',views.newperson, name = 'newperson'),
    path('add/',views.add,name = 'add'),
    path('<int:person_id>/edit/',views.edit,name ='edit'),
    path('<int:person_id>/save/',views.save,name = 'save'),
    path('<int:person_id>/delete/',views.delete,name = 'delete'),

]

contactandtodo/contactandtodo/urls.py
from django.contrib import admin
from django.urls import include,path
from . import views
urlpatterns = [
    path('',views.index, name = 'index'),
    path('contact/',include('contact.urls'),name = 'contact'),
    path('tododemo/',include('todo_demo.urls'),name = 'todo'),
    path('admin/', admin.site.urls),
]

contactandtodo/todo_demo/urls.py
from django.urls import path

from . import views
app_name = 'todo_demo'
urlpatterns = [
    path('',views.index, name = 'index'),
    path('todoitem/',views.TodoItemFunc, name = 'TodoItem'),
    path('add/',views.add,name = 'add'),
    path('<int:todo_id>/edit/',views.edit,name = 'edit'),
    path('save/',views.save,name = 'save'),
    path('<int:id>/delete/',views.delete,name = 'delete'),

]

contactandtodo/contact/models.py
from django.db import models

class Person(models.Model):
    person_name = models.CharField(max_length = 200)
    person_phone = models.CharField(max_length = 200)
    person_photo = models.ImageField(upload_to='contact/photo/',
                             blank=True)

contactandtodo/todo_demo/models.py
from django.db import models

class Status(models.Model):
    status_text = models.CharField(max_length = 200)
    def __str__(self):
        return self.status_text
class TodoItem(models.Model):
    todo_text = models.CharField(max_length=200)
    todo_status = models.ForeignKey(Status,on_delete=models.CASCADE)
    def __str__(self):
        return self.todo_text

contactandtodo/contact/views.py
from django.shortcuts import get_object_or_404,render
from django.http import HttpResponse,HttpResponseRedirect
from django.template import loader
from django.http import Http404
from .models import Person
from django.urls import reverse


def index(request):
    person_list = Person.objects.all
    return render(request,'contact/index.html',{'person_list':person_list})
def newperson(request):
    return render(request,'contact/newpersonform.html')
def add(request):
    name = request.POST['person_name']
    phone = request.POST['person_phone']
    photo = request.POST['person_photo']

    p = Person(person_name = name, person_phone = phone, person_photo = photo)
    p.save()
    return HttpResponseRedirect(reverse('contact:index'))
def edit(request,person_id):
    name = Person.objects.get(pk = person_id).person_name
    phone = Person.objects.get(pk = person_id).person_phone
    photo = Person.objects.get(pk = person_id).person_photo

    return render(request, 'contact/edit.html',{'name':name,'phone':phone,'photo':photo,'id':person_id})
def save(request, person_id):
    name = request.POST['person_name']
    phone = request.POST['person_phone']
    photo = request.POST['person_photo']
    Person.objects.filter(pk = person_id).update(person_name = name, person_phone = phone, person_photo = photo)
    return HttpResponseRedirect(reverse('contact:index'))

def delete(request, person_id):
    Person.objects.filter(pk = person_id).delete()
    return HttpResponseRedirect(reverse('contact:index'))

contactandtodo/contactandtodo/views.py
from django.shortcuts import get_object_or_404,render
from django.http import HttpResponse,HttpResponseRedirect
from django.template import loader
from django.http import Http404

from django.urls import reverse


def index(request):
    return HttpResponse("Hello")

contactandtodo/todo_demo/views.py
from django.shortcuts import get_object_or_404,render
from django.http import HttpResponse,HttpResponseRedirect
from django.template import loader
from django.http import Http404
from .models import Status,TodoItem
from django.urls import reverse
# Create your views here.
def index(request):
    todo_list = TodoItem.objects.all
    return render(request,'todo_demo/index.html',{'todo_list':todo_list})

def TodoItemFunc(request):
    return render(request,'todo_demo/TodoItem.html',{'statusList':Status.objects.all})

def add(request):
    text = request.POST['todo_text']
    status = request.POST['status']
    s = Status.objects.get(pk = status)
    todoItem = s.todoitem_set.create(todo_text = text)
    return HttpResponseRedirect(reverse('todo_demo:index'))

def edit(request, todo_id):
    text = TodoItem.objects.get(pk = todo_id).todo_text
    status = TodoItem.objects.get(pk = todo_id).todo_status

    Status.objects.get(pk = status.id).todoitem_set.get(pk = todo_id).delete()
    return render(request, 'todo_demo/edit.html',{'text':text,'status':status,'id':todo_id,'statusList':Status.objects.all})

def save(request):
    text = request.POST['todo_text']
    status = request.POST['status']
    s = Status.objects.get(pk = status)
    todoItem = s.todoitem_set.create(todo_text = text)
    return HttpResponseRedirect(reverse('todo_demo:index'))
def delete(request,id):
    
    return HttpResponseRedirect(reverse('todo_demo:index'))

contactandtodo/contact/templates/contact/edit.html
{% load static %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

<h1> Edit person</h1>
<form action = "{% url 'contact:save' id %}" method = "post"class="needs-validation">
  {% csrf_token %}
  <div class="col-md-6 mb-3">
    <label for="name">Name</label>
    <input class="form-control" type = "text" name="person_name" id = "person_name" value = "{{name}}"/>
  </div>
  <br/>
  <div class="col-md-6 mb-3">
    <label for="phone">Phone</label>
    <input class="form-control" type = "text" name="person_phone" id = "person_phone" value = "{{phone}}"/>
  </div>
  <br/>
  <div class="col-md-6 mb-3">
    <label for="photo">Photo</label>
    <input class="form-control" type = "text" name="person_photo" id = "person_photo" value = "{{photo}}"/>
  </div>
  <br/>
  <input type = "submit" value = "Submit" class="btn btn-primary btn-lg "/>
</form>
<form action = "{% url 'contact:delete' id%}" method = "post">
  {% csrf_token %}
  <input type = "submit" value = "Delete" class="btn btn-primary btn-lg " />
</form>

contactandtodo/contact/templates/contact/index.html
{% load static %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<link rel="stylesheet" type="text/css" href="{% static 'contact/style.css' %}" />
<h1>Contacts</h1>
<ul class="col-md-4">
  {% for person in person_list%}
  <li class="card mb-4 box-shadow" ><a href = "{% url 'contact:edit' person.id%}">
    <div class="row">
      <img src="{{ person.person_photo }}" style="height: 100px; width: 100px; margin: auto; margin-left:20px;"/>
      <div class="card-body">
        <p class="lead text-muted">Person name:</p>
        <p class="card-text">
          {{person.person_name}}
        </p>
        <p class="lead text-muted">Person phone:</p>
        <p class="card-text">
          {{person.person_phone}}
        </p>
    </div>
  </div>
  </a></li>
  {% endfor %}
</ul>

<form action = "{% url 'contact:newperson' %}" method = "post">
  {% csrf_token %}
  <input type="submit" value="Add person" class="btn btn-primary btn-lg"/>
</form>

contactandtodo/contact/templates/contact/newpersonform.html
{% load static %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

<h1> Add a new person</h1>
<form action = "{% url 'contact:add' %}" method = "post" class="needs-validation">
  {% csrf_token %}
  <div class="col-md-6 mb-3">
    <label for="name">Name</label>
    <input class="form-control" type = "text" name="person_name" id = "person_name" value = ""/>
  </div>
  <br/>
  <div class="col-md-6 mb-3">
    <label for="phone">Phone</label>
    <input class="form-control" type = "text" name="person_phone" id = "person_phone" value = ""/>
  </div>
  <br/>
  <div class="col-md-6 mb-3">
    <label for="photo">Photo</label>
    <input class="form-control" type = "text" name="person_photo" id = "person_photo" value = ""/>
  </div>
  <br/>
  <input type = "submit" value = "Submit" class="btn btn-primary btn-lg" />
</form>

contactandtodo/contactandtodo/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Hola</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
    crossorigin="anonymous">
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
</head>

<body>

  <nav class="navbar navbar-inverse">
    <a class="navbar-brand" href="/">Logo</a>
    <ul class="nav navbar-nav">
      <li >
        <a href="{% url 'contact' %}">Contact</a>
      </li>
      <li >
        <a href="{% url 'todo' %}">Todo</a>
      </li>
    </ul>
  </nav>


  <div class="container">

      {% block content %}

      {% endblock content %}

  </div>

</body>

</html>

contactandtodo/todo_demo/templates/todo_demo/TodoItem.html
{% load static %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

<h1> Add a new todo</h1>
<form action = "{% url 'todo_demo:add' %}" method = "post" class="needs-validation">
  {% csrf_token %}
  <div class="col-md-6 mb-3">
    <label for="text">Text</label>
    <input class="form-control" type = "text" name="todo_text" id = "todo_text" value = ""/>
  </div>
  <br/>
  {% for status in statusList%}
  <input type = "radio" name = "status" id = "status{{forloop.counter}}" value = "{{status.id}}"/>
  <label for="status{{forloop.counter}}">{{status.status_text}}</label>
  <br/>
  {%endfor%}
  <input type = "submit" value = "submit" class="btn btn-primary btn-lg "/>
</form>

contactandtodo/todo_demo/templates/todo_demo/edit.html
{% load static %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

<h1> Edit a todo</h1>
<form action = "{% url 'todo_demo:save' %}" method = "post" class="needs-validation">
  {% csrf_token %}
  <div class="col-md-6 mb-3">
    <label for="text">Text</label>
    <input class="form-control" type = "text" name="todo_text" id = "todo_text" value = "{{text}}"/>
  </div>
  <br/>
  {% for status in statusList%}
  <input type = "radio" name = "status" id = "status{{forloop.counter}}" value = "{{status.id}}"/>
  <label for="status{{forloop.counter}}">{{status.status_text}}</label>
  <br/>
  {%endfor%}
  <input type = "submit" value = "Submit" class="btn btn-primary btn-lg " />

</form>
<form action = "{% url 'todo_demo:delete' id%}" method = "post" >
  {% csrf_token %}
  <input type = "submit" value = "Delete" class="btn btn-primary btn-lg "/>
</form>

contactandtodo/todo_demo/templates/todo_demo/index.html
{% extends "../contactandtodo/templates/base.html" %}
{% load static %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<link rel="stylesheet" type="text/css" href="{% static 'todo_demo/style.css' %}" />
{% block content %}
<h1>Todo</h1>
<ul class="col-md-4">
  {% for item in todo_list%}
  <li class="card mb-4 box-shadow"><a href = {% url 'todo_demo:edit' item.id %}>
    <div class="card-body">
      <p class="lead text-muted">Text:</p>
      <p class="card-text">
        {{item.todo_text}}
      </p>
      <p class="lead text-muted">Status:</p>
      <p class="card-text">
        {{item.todo_status}}
      </p>
  </div>

   </a> </li>
  {% endfor %}
</ul>
<form action = "{% url 'todo_demo:TodoItem' %}" method = "post">
  {% csrf_token %}
  <input type="submit" value="Add" class="btn btn-primary btn-lg "/>
</form>
{% endblock content %}